apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-nvitop-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-nvitop-exporter
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list