apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-nvitop-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-nvitop-exporter
spec:
  endpoints:
    - port: gpu-metrics
      path: "/metrics"
  jobLabel: app
  namespaceSelector:
    matchNames:
      - "FILLED BY THE OPERATOR"
  selector:
    matchLabels:
      app: nvidia-nvitop-exporter